version: "3"

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:16.0.5
    container_name: forgejo
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./data:/data
    restart: always
